package dev.enro.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.Project
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.provider.Provider
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.jetbrains.kotlin.gradle.plugin.KotlinCompilation
import org.jetbrains.kotlin.gradle.plugin.KotlinCompilerPluginSupportPlugin
import org.jetbrains.kotlin.gradle.plugin.KotlinPlatformType
import org.jetbrains.kotlin.gradle.plugin.SubpluginArtifact
import org.jetbrains.kotlin.gradle.plugin.SubpluginOption
import java.io.File

public class EnroGradleSubplugin : KotlinCompilerPluginSupportPlugin {

    override fun apply(target: Project) {
        target.extensions.create("enro", EnroGradlePluginExtension::class.java)
    }

    override fun getCompilerPluginId(): String = "dev.enro.plugin.enro-compiler"

    override fun getPluginArtifact(): SubpluginArtifact = SubpluginArtifact(
        groupId = "dev.enro",
        artifactId = "enro-compiler-plugin",
        version = BuildConfig.VERSION,
    )

    override fun isApplicable(kotlinCompilation: KotlinCompilation<*>): Boolean = true

    override fun applyToCompilation(
        kotlinCompilation: KotlinCompilation<*>,
    ): Provider<List<SubpluginOption>> {
        val project = kotlinCompilation.target.project
        val extension = project.extensions.getByType(EnroGradlePluginExtension::class.java)
        val enabled = extension.enabled.get()

        // Register the generate bindings task for this compilation
        registerGenerateBindingsTask(kotlinCompilation)

        return project.provider {
            listOf(
                SubpluginOption(key = "enabled", value = enabled.toString()),
            )
        }
    }

    private fun registerGenerateBindingsTask(kotlinCompilation: KotlinCompilation<*>) {
        val project = kotlinCompilation.target.project
        val targetName = kotlinCompilation.target.name
        kotlinCompilation.platformType
        val compilationName = kotlinCompilation.compilationName
        if (kotlinCompilation.platformType == KotlinPlatformType.common) {
            if (compilationName != "main") return
        }
        val moduleName = ("${project.rootProject.name}${project.path}")
            .replace(":", "_")
            .replace("-", "_")
            .trimStart('_')
            .trimEnd('_')
            .ifEmpty { "root" }

        val className = "EnroBindings_${moduleName}_${targetName}_${compilationName}"

        val taskName = "generateEnroBindings${targetName.replaceFirstChar { it.uppercaseChar() }}${compilationName.replaceFirstChar { it.uppercaseChar() }}"
        val outputDir = project.layout.buildDirectory.dir("generated/enro/$targetName/$compilationName")

        val generateTask =
            project.tasks.register(taskName, GenerateEnroBindingsTask::class.java) { task ->
                task.className.set(className)
                task.outputDirectory.set(outputDir)
                task.description = "Generates Enro bindings file for ${targetName}/${compilationName} compilation"
                task.group = "enro"
            }

        kotlinCompilation.defaultSourceSet.kotlin.srcDir(generateTask.map { it.outputDirectory })
    }
}

public abstract class GenerateEnroBindingsTask : DefaultTask() {

    @get:Input
    public abstract val className: Property<String>

    @get:OutputDirectory
    public abstract val outputDirectory: DirectoryProperty

    @TaskAction
    public fun generate() {
        val outputDir = outputDirectory.get().asFile
        val packageDir = File(outputDir, "enro_generated_bindings")
        packageDir.mkdirs()

        val className = className.get()
        val outputFile = File(packageDir, "$className.kt")

        val content = buildString {
            appendLine("// Generated by Enro Gradle Plugin - DO NOT EDIT")
            appendLine("package enro_generated_bindings")
            appendLine()
            appendLine("public object $className")
            appendLine()
            appendLine("public fun enroGeneratedBindingReference(reference: $className) {}")
        }
        outputFile.writeText(content)
    }
}